// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var StringUtils$Calc = require("./StringUtils.bs.js");

function toString(n) {
  if (!n) {
    return "()";
  }
  var t = n._0;
  var tmp;
  if (typeof t === "number") {
    switch (t) {
      case /* Plus */0 :
          tmp = "+";
          break;
      case /* Minus */1 :
          tmp = "-";
          break;
      case /* Multiply */2 :
          tmp = "*";
          break;
      case /* Divide */3 :
          tmp = "/";
          break;
      
    }
  } else {
    tmp = String(t._0);
  }
  return "(" + (StringUtils$Calc.join(" ", {
                hd: tmp,
                tl: {
                  hd: toString(n._1),
                  tl: {
                    hd: toString(n._2),
                    tl: /* [] */0
                  }
                }
              }) + ")");
}

exports.toString = toString;
/* No side effect */
