// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_string = require("bs-platform/lib/js/caml_string.js");

function explode(str) {
  var _index = str.length - 1 | 0;
  var _chars = /* [] */0;
  while(true) {
    var chars = _chars;
    var index = _index;
    if (index < 0) {
      return chars;
    }
    _chars = {
      hd: Caml_string.get(str, index),
      tl: chars
    };
    _index = index - 1 | 0;
    continue ;
  };
}

exports.explode = explode;
/* No side effect */
