// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Tokenizer$Calc = require("../src/Tokenizer.bs.js");

Jest.describe("tokenize", (function (param) {
        Jest.test("space", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: /* [] */0
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("")));
              }));
        Jest.test("spaces", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: /* [] */0
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("    ")));
              }));
        Jest.test("number", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* Number */{
                                _0: 17
                              },
                              tl: /* [] */0
                            }
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("17")));
              }));
        Jest.test("explicitly positive number", (function (param) {
                var res = Tokenizer$Calc.tokenize("+12");
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* Plus */0,
                              tl: {
                                hd: /* Number */{
                                  _0: 12
                                },
                                tl: /* [] */0
                              }
                            }
                          }, Jest.Expect.expect(res));
              }));
        Jest.test("negative number", (function (param) {
                var res = Tokenizer$Calc.tokenize("-12");
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* Minus */1,
                              tl: {
                                hd: /* Number */{
                                  _0: 12
                                },
                                tl: /* [] */0
                              }
                            }
                          }, Jest.Expect.expect(res));
              }));
        Jest.test("mixed numbers", (function (param) {
                var res = Tokenizer$Calc.tokenize("17 0 123 -1");
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* Number */{
                                _0: 17
                              },
                              tl: {
                                hd: /* Number */{
                                  _0: 0
                                },
                                tl: {
                                  hd: /* Number */{
                                    _0: 123
                                  },
                                  tl: {
                                    hd: /* Minus */1,
                                    tl: {
                                      hd: /* Number */{
                                        _0: 1
                                      },
                                      tl: /* [] */0
                                    }
                                  }
                                }
                              }
                            }
                          }, Jest.Expect.expect(res));
              }));
        Jest.test("operators", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* Plus */0,
                              tl: {
                                hd: /* Minus */1,
                                tl: {
                                  hd: /* Multiply */2,
                                  tl: {
                                    hd: /* Divide */3,
                                    tl: /* [] */0
                                  }
                                }
                              }
                            }
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("+ - * /")));
              }));
        Jest.test("parens", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* OpenParens */4,
                              tl: {
                                hd: /* CloseParens */5,
                                tl: /* [] */0
                              }
                            }
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("( )")));
              }));
        Jest.test("sticky parens", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* OpenParens */4,
                              tl: {
                                hd: /* OpenParens */4,
                                tl: {
                                  hd: /* CloseParens */5,
                                  tl: {
                                    hd: /* CloseParens */5,
                                    tl: /* [] */0
                                  }
                                }
                              }
                            }
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("(())")));
              }));
        Jest.test("expression", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* Number */{
                                _0: 1
                              },
                              tl: {
                                hd: /* Plus */0,
                                tl: {
                                  hd: /* Number */{
                                    _0: 3
                                  },
                                  tl: /* [] */0
                                }
                              }
                            }
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("1 + 3")));
              }));
        Jest.test("compact expression", (function (param) {
                return Jest.Expect.toEqual({
                            TAG: /* Ok */0,
                            _0: {
                              hd: /* Number */{
                                _0: 1
                              },
                              tl: {
                                hd: /* Plus */0,
                                tl: {
                                  hd: /* Number */{
                                    _0: 3
                                  },
                                  tl: /* [] */0
                                }
                              }
                            }
                          }, Jest.Expect.expect(Tokenizer$Calc.tokenize("1+3")));
              }));
        return Jest.test("bad char", (function (param) {
                      return Jest.Expect.toEqual({
                                  TAG: /* Error */1,
                                  _0: "unexpected character {"
                                }, Jest.Expect.expect(Tokenizer$Calc.tokenize("1*{3-2}")));
                    }));
      }));

/*  Not a pure module */
